### ISSUE TITLE
安装无法成功

### ISSUE THREAD

**Issue by JrontEnd** [ETENG-OSP/xgpush-cordova#18]
Installing "cordova-plugin-xgpush" for android
Error during processing of action! Attempting to revert...
Failed to install 'cordova-plugin-xgpush':Error: Uh oh!
"/Users/jiaoxiangyu/WebstormProjects/VIS/plugins/cordova-plugin-xgpush/sdk/android/libs/Xg_sdk_v2.41_20150915_1121.jar" not found!
    at Object.module.exports.common.copyFile (/Users/jiaoxiangyu/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:38:40)
    at Object.module.exports.common.copyNewFile (/Users/jiaoxiangyu/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/common.js:69:16)
    at module.exports.source-file.install (/Users/jiaoxiangyu/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:78:20)
    at /Users/jiaoxiangyu/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:653:27
    at Object.ActionStack.process (/Users/jiaoxiangyu/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/cordova-common/src/ActionStack.js:56:25)
    at PlatformApiPoly.addPlugin (/Users/jiaoxiangyu/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/PlatformApiPoly.js:259:20)
    at handleInstall (/Users/jiaoxiangyu/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:603:6)
    at /Users/jiaoxiangyu/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:382:28
    at _fulfilled (/Users/jiaoxiangyu/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/jiaoxiangyu/.nvm/versions/node/v5.1.0/lib/node_modules/cordova/node_modules/q/q.js:816:30)
Error: Uh oh!
"/Users/jiaoxiangyu/WebstormProjects/VIS/plugins/cordova-plugin-xgpush/sdk/android/libs/Xg_sdk_v2.41_20150915_1121.jar" not found!

**Comment by gengen1988** [comment]
ok，看起来是 jar 改名了

```text
xgpush/sdk/android/libs/Xg_sdk_v2.41_20150915_1121.jar" not found!
```
