### ISSUE TITLE
Android build 失敗

### ISSUE THREAD

**Issue by demiurga** [ETENG-OSP/xgpush-cordova#19]
```
:preDexArmv7Debug
:dexArmv7Debug

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:dexArmv7Debug FAILED
```
如題，是哪裡出錯了呢？

**Comment by gengen1988** [comment]
可能其他 plugin 也依赖了 android support v4。把你用到的 plugin 分享一下我看看？

参考：http://stackoverflow.com/questions/20989317/multiple-dex-files-define-landroid-support-v4-accessibilityservice-accessibility

**Comment by demiurga** [comment]
google了一下 似乎跟這個有關
https://github.com/phonegap-build/PushPlugin/issues/492

把libs裡的android.support.v4.jar刪除之後就build過了，感謝樓主
